package com.securenotes.api.entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * A note owned by one user.
 */
@Entity
@Table(name = "notes")
public class NoteEntity extends PanacheEntityBase {

    /**
     * Primary key generated by PostgreSQL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    /**
     * User with full read, write, delete, and share privileges for this note.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    public AppUser owner;

    /**
     * Note body.
     */
    @Column(nullable = false, columnDefinition = "text")
    public String content;

    /**
     * Timestamp when the note was created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    public Instant createdAt;

    /**
     * Timestamp when the note was last changed.
     */
    @Column(name = "updated_at", nullable = false)
    public Instant updatedAt;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }
}
